### ISSUE TITLE
Download uploaded image

### ISSUE THREAD

**Issue by nick70007** [pexavc/IPFSKit#2]
In my SwiftUI App i have managed to upload images to ipfs server but cannot able to download as per the method change from get to post. Is there any workaround? Do let me know. Thanks

**Comment by boni1000** [comment]
Hi! I'm pretty new in IPFS field. Can you suggest me where can I find more detail documentation regarding how to download files from IPFS using this library. Thank you in advance!

**Comment by pexavc** [comment]
> In my SwiftUI App i have managed to upload images to ipfs server but cannot able to download as per the method change from get to post. Is there any workaround? Do let me know. Thanks

The gateway hash should technically be the endpoint to create a get request to download the target asset. Apologies for getting to these issues so late. But, let me know if you need any help, I will circle back on updating this implementation soon to keep it up to date to infura's recent changes.

@nick70007

**Comment by pexavc** [comment]
@nick70007 @boni1000 I am back to updating this package. Sorry for the delay as I have been really busy with personal life last year. 

I seem to be able to download. But, this time around I am adding a whole interface for actions like that, that will be easier to invoke.
